### ISSUE TITLE
Add STATIC_ROOT setting

### ISSUE THREAD

**Issue by raybesiga** [makaimc/city-chat#1]
Hey @makaimc 

Loving the tutorials and keenly following you on here. Just thought to point out that that `chat.js` 404 error persists on inspection until you add to the settings

```
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
```

And then it runs perfectly. Cheers.

R

**Comment by mattmakai** [comment]
that's weird, I don't think I ran into that but I think it's best to call out the STATIC_ROOT explicitly. I made an update, thank you @raybesiga

**Comment by raybesiga** [comment]
You're welcome @makaimc :)
